apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnwebapp
  labels:
    app: vulnwebapp
spec:
  selector:
    matchLabels:
      app: vulnwebapp
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: vulnwebapp
        tier: frontend
    spec:
      containers:
      - name: vulnwebapp
        image: docker.io/cybersmithio/vulnwebapp:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: FLASK_APP
          value: vulnwebapp
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: vulnwebapp
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: vulnwebapp
    tier: frontend
